### ISSUE TITLE
Export to text doesn't map persistentIDs to names

### ISSUE THREAD

**Issue by hmijail** [cvzi/itunes_smartplaylist#5]
When using utils/export.py on a library that has smart playlists that depend on another playlist, the generated text files list "PlaylistPersistentID is `<hex>`". 

I started looking into resolving those IDs to the playlist's names, and found that actually looks like there's already code to do that when exporting to .xsp files, including function `generatePersistentIDMapping`. However, the export.py file seems to do things slightly(?) differently?

So I thought I'd ask. Could you please implement the ID->name resolution for text exports? Or indicate how best to do it? I'm not a Python person but can try doing something that could be PR'd later.

**Comment by cvzi** [comment]
I will take a look

**Comment by cvzi** [comment]
To clarify:

You are looking for the output of utils/export.py with 
`PlaylistPersistentID is <hex>` replaced by something like `PlaylistName is "<name>"`.

The simplest way would be to take the output and use a regular expression to find and replace. As you noted, the mapping is already there, just not used at the moment.  

If that is what you need, I can definitely change the script to make it do that.

**Comment by hmijail** [comment]
Yes, that's what I'd like.

**Comment by cvzi** [comment]
I added the mapping to export.py as I described above.

While testing it I also found a bug that is now fixed: the PlaylistPersistentIDs were not zero-padded correctly. Now they should be the same as in the iTunes xml file.

**Comment by hmijail** [comment]
Thank you for this. 
It has a problem: when a Persistent ID starts with 0s, looks like the mapping doesn't work.
In my case I get this error:
> No playlist with Persistent ID '3E249B3B9A17147' (mentinoned in playlist 'salsa, >3*')

But actually there is a playlist in the XML with the ID '**0**3E249B3B9A17147'.

**Comment by hmijail** [comment]
(I see that #6 probably should fix this, and yet I'm seeing this in commit b893f5e4ab784f4c4041d91e10eee296f72b893d )

**Comment by cvzi** [comment]
I think you may have previously installed the package, and now the export.py scripts imports your installed (old) version, instead of importing directly from the parent directory. 

With 4fc6f349c03a4b09df055cee258d6f907f466772 it should try to import from the parent directory first.
I am not completely sure though, maybe you have to uninstall and reinstall the package with `pip uninstall itunessmart` and `pip install --upgrade itunessmart`.

Thanks for the PR!

**Comment by hmijail** [comment]
I pulled commit 34e5674b3fb039c7dc289850a0a422e07334716a , retried and now it worked perfectly. Thank you!
